// NOTE: Do not edit this file. It is built by running `/codegen/pages.js`

import Calendarpage from './pages/calendarpage/calendarpage.jsx';
import Externalpackages from './pages/externalpackages/externalpackages.jsx';
import PageIndex from './pages/page-index/page-index.jsx';

export default [
  {
    component: Calendarpage,
    group: 'Pages',
    name: 'Calendarpage',
    path: '/calendarpage',
  },
  {
    component: Externalpackages,
    group: 'Pages',
    name: 'Externalpackages',
    path: '/externalpackages',
  },
  {
    component: PageIndex,
    group: '',
    name: 'Page Index',
    path: '/',
  },
];
